name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake -Dtest=ON ../
    - name: make
      run: cd build && make
    - name: make test
      run: cd build && make test
    - name: make doc
      run: cd build && make doc
